2022-03-27 22:21:23,002 - instabot version: 0.117.0 (bot) - INFO - Instabot version: 0.117.0 Started
2022-03-27 22:21:23,003 - instabot version: 0.117.0 (bot) - DEBUG - Bot imported from /home/achyuth/.local/lib/python3.9/site-packages/instabot/bot/bot.py
2022-03-27 22:21:23,004 - instabot version: 0.117.0 (api_login) - INFO - Not yet logged in starting: PRE-LOGIN FLOW!
2022-03-27 22:21:23,405 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/get_prefill_candidates/ returned response: <Response [200]>
2022-03-27 22:21:24,262 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: qe/sync/ returned response: <Response [200]>
2022-03-27 22:21:24,842 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: launcher/sync/ returned response: <Response [200]>
2022-03-27 22:21:25,245 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/contact_point_prefill/ returned response: <Response [200]>
2022-03-27 22:21:28,421 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/login/ returned response: <Response [400]>
2022-03-27 22:21:28,421 - instabot version: 0.117.0 (api) - DEBUG - Responsecode indicates error; response content: b'{"message":"challenge_required","challenge":{"url":"https://i.instagram.com/challenge/AXFZowa27vFmJ1SULy1BZxf4ZAODvd7YDtMNo-M9ClPc0QFZ0OuoZuZiI_KyyUNynf3B44c/Ma6YIGxigqFnE9u2/","api_path":"/challenge/AXFZowa27vFmJ1SULy1BZxf4ZAODvd7YDtMNo-M9ClPc0QFZ0OuoZuZiI_KyyUNynf3B44c/Ma6YIGxigqFnE9u2/","hide_webview_header":true,"lock":true,"logout":false,"native_flow":true,"flow_render_type":0},"status":"fail","error_type":"checkpoint_challenge_required"}'
2022-03-27 22:21:28,421 - instabot version: 0.117.0 (api) - ERROR - Request returns 400 error!
2022-03-27 22:21:28,422 - instabot version: 0.117.0 (api) - INFO - Instagram's error message: challenge_required
2022-03-27 22:21:28,422 - instabot version: 0.117.0 (api) - INFO - Error type: checkpoint_challenge_required
2022-03-27 22:21:30,805 - instabot version: 0.117.0 (api_photo) - ERROR - Photo Upload failed with the following response: <Response [403]>
2022-03-27 22:21:30,806 - instabot version: 0.117.0 (bot_photo) - INFO - Photo 'demo.jpg' is not uploaded.
