2022-03-27 22:26:17,529 - instabot version: 0.117.0 (bot) - INFO - Instabot version: 0.117.0 Started
2022-03-27 22:26:17,530 - instabot version: 0.117.0 (bot) - DEBUG - Bot imported from /home/achyuth/.local/lib/python3.9/site-packages/instabot/bot/bot.py
2022-03-27 22:26:17,532 - instabot version: 0.117.0 (api_login) - INFO - Not yet logged in starting: PRE-LOGIN FLOW!
2022-03-27 22:26:21,591 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/get_prefill_candidates/ returned response: <Response [200]>
2022-03-27 22:26:22,716 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: qe/sync/ returned response: <Response [200]>
2022-03-27 22:26:23,845 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: launcher/sync/ returned response: <Response [200]>
2022-03-27 22:26:25,272 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/contact_point_prefill/ returned response: <Response [200]>
2022-03-27 22:26:28,300 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/login/ returned response: <Response [400]>
2022-03-27 22:26:28,301 - instabot version: 0.117.0 (api) - DEBUG - Responsecode indicates error; response content: b'{"message":"challenge_required","challenge":{"url":"https://i.instagram.com/challenge/AXG6IVrUeoFWEhQ0Rut8S26-Z7rB4SpKeUOdHX8P2f9wikX3nhFStL9PVjfeXf9A-kf8MZ4/dVSI82G3ts09cyXu/","api_path":"/challenge/AXG6IVrUeoFWEhQ0Rut8S26-Z7rB4SpKeUOdHX8P2f9wikX3nhFStL9PVjfeXf9A-kf8MZ4/dVSI82G3ts09cyXu/","hide_webview_header":true,"lock":true,"logout":false,"native_flow":true,"flow_render_type":0},"status":"fail","error_type":"checkpoint_challenge_required"}'
2022-03-27 22:26:28,301 - instabot version: 0.117.0 (api) - ERROR - Request returns 400 error!
2022-03-27 22:26:28,301 - instabot version: 0.117.0 (api) - INFO - Instagram's error message: challenge_required
2022-03-27 22:26:28,302 - instabot version: 0.117.0 (api) - INFO - Error type: checkpoint_challenge_required
2022-03-27 22:26:29,645 - instabot version: 0.117.0 (api_photo) - ERROR - Photo Upload failed with the following response: <Response [403]>
2022-03-27 22:26:29,646 - instabot version: 0.117.0 (bot_photo) - INFO - Photo 'demo.jpg' is not uploaded.
